#!/usr/bin/env bash

dry="0"

while [[ $# > 0 ]]; do
	if [[ "$1" == "--dry" ]]; then
		dry="1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[[DRY_RUN]]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

copy_dir() {
	from=$1
	to=$2

	pushd $from >/dev/null
	dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
	for dir in $dirs; do
		execute mkdir -p $to
		execute cp -r $dir $to/$dir
	done
	popd >/dev/null
}
copy_file() {
	from=$1
	to=$2
	files=$(find $from -mindepth 1 -maxdepth 1 -type f)
	for file in $files; do
		name=$(basename $file)
		execute cp $file $to/$name
	done
}
if find ~/.config -mindepth 1 -maxdepth 1 -type d | grep -q nvim; then
	echo "Copying nvim config"
	copy_dir ~/.config/nvim ~/personal/dev-env/.config/backup-nvim
	copy_file ~/.config/nvim ~/personal/dev-env/.config/backup-nvim
else
	echo "nvim config not found"
	exit 0
fi
