#!/usr/bin/env bash

selected=$(find ~/Documents/Code ~/Documents/frontend -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t $selected_name 2>/dev/null; then
	switch_to
else
	tmux new-session -ds $selected_name -c $selected
	tmux new-window -t $selected_name -n 'scratch' -c $selected
	switch_to
	tmux send-keys -t $selected_name:scratch "nvim ." Enter
	echo "Created new session $selected_name at $selected."
fi
